version: "3.8"
services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          echo "sleep for 5sec"
          sleep 5
          npm run start:dev

  nginx:
    volumes:
      - ./files/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5002:80"