version: "3.8"
services:
  api:
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - ./.env
    environment:
      RUNTIME: DOCKER
    container_name: estate_api
    restart: unless-stopped
    depends_on:
      database:
        condition: service_started
      mongo:
        condition: service_started
    networks:
      - estate

  nginx:
    image: nginx
    networks:
      - estate
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started

  database:
    image: postgres:13
    container_name: estate_postgres_database
    volumes:
      - estate_postgres_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - estate

  mongo:
    image: mongo
    container_name: estate_mongo_database
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: 
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ADMIN_PWD}
    volumes:
      - estate_mongo_db_data:/data/db
    networks:
      - estate

  redis:
    image: redis
    container_name: estate_redis
    volumes:
      - estate_redis_data:/data
    restart: unless-stopped
    networks:
      - estate

networks:
  estate:
volumes:
  estate_mongo_db_data:
  node_modules:
  estate_postgres_db_data:
  estate_redis_data:
